### ISSUE TITLE
New machine different MAC address

### ISSUE THREAD

**Issue by Denist79** [xhente/omv-regen#1]
I tried the script using a config file from one machine and tried to restore but error arise about different MAC address and then cannot login to the webgui after reboot. 

Is there not a way to use this process if you want to move to a different machine or is this only for existing machines. 

Thanks.

**Comment by xhente** [comment]
The last step of the script is the regeneration of the network interface. At that time, a message is displayed on the screen for 10 seconds that allows you to bypass this setting from the network interface by pressing any key. Then the current network settings will be kept.
This should allow installation on any machine.

**Comment by Denist79** [comment]
Ok, would it not be beneficial for the script to stop at the end asking is this a new machine or restoring an original OMV6 and you can answer yes or no  then it proceeds. 

I am trying to restore the config on another machine to test it just in case I have a board failure and this would be beneficial. 

I am also getting this error sometimes trying to restore. sometimes it goes through other times the below is displayed. 

“The OMV version of the original server does not match. Exiting…”

And now it cannot proceed due to this error and would need to reinstall OMV again to try and restore. 

Any tips

thanks.

**Comment by Denist79** [comment]
I forgot to add the -b and I think I jammed it heheh. Trying again.

**Comment by Denist79** [comment]
Tried again and same thing happened not sure why it’s not working.

**Comment by xhente** [comment]
This is a limitation of the script. Regeneration depends on the version of each package available on the Internet being the same as the one installed on the original system. If they are different versions the format of the fields in the database could also be different. This would create problems.
I can't do anything about it if there are no older versions on the internet.
That is why it is warned in the documentation that it is convenient to make the backup and immediately do the regeneration. If a version of a package has been updated between the two steps the regeneration will not be possible.

**Comment by Denist79** [comment]
It looks like there was an OMV update that halted the restore. The script downloads the latest OMV update but the retire files are older and the. It halts the restore process. Any ways this can be done differently or is this a limitation where the backup and updates have to be current and matching. 

Thanks.

**Comment by Denist79** [comment]
> > Ok, would it not be beneficial for the script to stop at the end asking is this a new machine or restoring an original OMV6 and you can answer yes or no then it proceeds.
> 
> Paralyzing the script may not be convenient, I prefer an unattended installation, although it is possible to kill, otherwise the script continues. I could add an option to schedule this before launching the script, I'll look into that.
> 
> > “The OMV version of the original server does not match. Exiting…”
> 
> This is a limitation of the script. Regeneration depends on the version of each package available on the Internet being the same as the one installed on the original system. If they are different versions the format of the fields in the database could also be different. This would create problems. I can't do anything about it if there are no older versions on the internet. That is why it is warned in the documentation that it is convenient to make the backup and immediately do the regeneration. If a version of a package has been updated between the two steps the regeneration will not be possible.

Makes sense thanks.

**Comment by xhente** [comment]
Added option to skip network regeneration.
