### ISSUE TITLE
Don't backup /home unless -o is specified

### ISSUE THREAD

**Issue by dacmot** [xhente/omv-regen#2]
Hello. Thank you for the great script! I'm really happy I found it.

I tried the script with only the -b option, and it started doing the backup of my /home folder. Since my /home folder is quite big, I do a separate backup for it. It would be great if /home wasn't backed up unless -o was specified, or that another (new) option would disable folder backup.

**Comment by xhente** [comment]
I would remove the /home path from the default paths, it's easy to do. But I'm worried that someone thinks that folder is being copied and it really isn't.
On the other hand, I don't like to create an option just for this either. The script already has many options, perhaps too many.
When I wrote it I didn't think someone could have that much data in /home, OMV's default behavior is to store data away from rootfs.
I need to think about this.
You can temporarily manually edit the `/usr/sbin/omv-regen` file and on line 34 remove the `"/home"` folder, this will cause it to not be included.
That line would look like this:
`declare -a Directories=("/etc/libvirt" "/var/lib/libvirt")`

**Comment by xhente** [comment]
Solved with omv-regen 2.0
