### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by gitrosers** [xhente/omv-regen#3]
I tried to run the script once to see how it works but then it seems like it is saved and installed somewhere.  Can you add a script to uninstall everything?

**Comment by xhente** [comment]
All the installation does is copy a file to /usr/sbin/omv-regen
So you just need to delete that file:
`rm /usr/sbin/omv-regen`
If you have created any scheduled tasks in the OMV GUI delete it too. There is nothing else.

**Comment by gitrosers** [comment]
got it, thanks much.
