### ISSUE TITLE
Restore Doesn't setup plugins

### ISSUE THREAD

**Issue by an0o0nym** [xhente/omv-regen#7]
Hi,
First of all big thanks for sharing your work!

I've just had to replace my usb stick as it started acting up. I've used omv-regen to create backup copy of my current omv config. I am using v 7.4.10-1.

Everything worked just fine. Although for some reason none of the plugins have been installed (luks, compose, flashmemory etc.)

Should I install all those plugins manually? Run omv-regen once again on already restored config?

What would be your suggestions to proceed in this case? 

Thanks

**Comment by an0o0nym** [comment]
OK. I ran `omv-regen` once again. It works all fine now. Somehow I missed the part in your README.

> A reboot may be required during the process, if so omv-regen will ask you to do so, after the reboot run omv-regen again, the process will continue automatically.

**Comment by an0o0nym** [comment]
I didn't read the detailed instruction on Step 3. I had to use omv-regen few times in between reboots. It is all now working perfectly fine.

> A reboot may be required during the process, if so omv-regen will ask you to do so, after the reboot run omv-regen again, the process will continue automatically.

**Comment by xhente** [comment]
Before the reboot the script displays a message warning that it is necessary to run omv-regen again after the reboot.
I have modified the script so that the user must accept the reboot message, that way the user will necessarily be warned before the reboot.
I hope that helps.
